"""Add role and staff model

Revision ID: b3678250d1c8
Revises: bcc8360f9d56
Create Date: 2025-04-05 18:28:01.383431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3678250d1c8'
down_revision = 'bcc8360f9d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('staff')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('role_name')

    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('role_name', ['role_name'], unique=True)

    op.create_table('staff',
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_no', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='staff_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.drop_table('roles')
    # ### end Alembic commands ###
